os: osx
dist: trusty
language: node_js
node_js: v10
install:
  - npm i
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: smilingxinyi@gmail.com
  skip_cleanup: true
  api_key:
    secure: sQm1kR67jGuRDuNxa682rzlJG6ilFpn4OwOdB3hRAlsHpf+mAm6HTSJEvuy71trxqO4Lo4cbyOAGRth884JMhehQ28OpBNnzY78WBpQqgkP0WJ4cPpYQPfZdxrdXxdoUP2mw3+YBKskFOlRg1UhmImjmTwNeY926iZTznliVjLfodDcrKO2h/pibtSfQximuSJNeTXjUACGS8ml0k1dqhf+jM7//HCMB1nCfgzG90C2bL5dtLTLfkjh3nnjyYkuU8MawcM7kPRIdpR5gBKjmvBYtGhITd1ROJvyKA6Sczen7P081li8DPjwrATKSIeD4JpdDgFr5zesD2n7UkNrjpttcvAbo6Xp23GZCGnrxOg+mGJcOUAnkCLHXRVD6QYOECQqZKdkCfSYruGJDG58L2Q5140Ag6J5IDOR+pwyEGnwsdsF1pKAZkDTEzatw/mBucUyVV3PWyVv0SBx/68lMXS2jCEB5h12KA0gKdhxpBIe3xf4NEHWuSWoAUEOdd7Q+YMioiA5XCG+zb2ZSykh0Zzff2AoEvmbfKitlRhNjgrMXdJD0SESWkARYYX8KJh9vLnQ15iihLu+lR3f4FsxWJIGm7f3ODTN8nQkDP+oCd6s1kw3qcrglDKFSrPk24hlhRc/G550Wv1zSSzoQKLvAqFEAvREgom4Hxzgu0X6jt0Q=
  on:
    tags: true
    repo: misaka-ink/doT-template
